package:
  name: ptsa
  version: 1.1.3

source:
  git_url: ../

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

  # Specify additional env vars pass through
  script_env:
    - PYTHON_BUILD_VERSION

requirements:
  build:
    - python {{ environ.get("PYTHON_BUILD_VERSION", "3.6") }}*
    - numpy
    - scipy
    - xarray
    - pywavelets
    - swig
    - pytables
    - setuptools

  run:
    #- python {{ environ.get("PYTHON_BUILD_VERSION", "3.6") }}*
    - python {{PY_VER}}*
    - numpy
    - scipy
    - xarray
    - pywavelets
    - pytables
    - vs2015_runtime  [win]

test:
  # Test that we can import ptsa and its extension modules
  imports:
    - ptsa
    - dimarray
    - ptsa.extensions.morlet
    - ptsa.extensions.circular_stat

about:
  home: https://github.com/pennmem/ptsa_new
  license: GPLv3
  license_file: LICENSE
